### ISSUE TITLE
Samples Broken in 1.15

### ISSUE THREAD

**Issue by patelsan** [aws-samples/pyflink-getting-started#10]
Looks like the Getting Started doesn't work anymore with version 1.15 supported by Kinesis. Looks like the following API has changed

`env_settings = (
    EnvironmentSettings.new_instance().in_streaming_mode().use_blink_planner().build()
)`

Tried changing that to the static method, but that also fails with a cryptic error. 

`EnvironmentSettings.in_streaming_mode()`

Could you please update the samples to work with latest version on Kinesis - 1.15. Thanks!

**Comment by patelsan** [comment]
Just tried creating Analytics App with Flink version 1.13, and looks like that is also unable to run this code. Here are the errors:

![image](https://user-images.githubusercontent.com/898353/212494557-524c0475-6220-44c3-8f81-d1d47284f61f.png)

**Comment by jeremyber-aws** [comment]
hi @patelsan I've updated the repo to include v1.13 and v1.15 examples respectively. The main branch will now feature the latest version that KDA supports (currently v1.15). Please let me know if this update works for you.

**Comment by patelsan** [comment]
Thank you @jeremyber-aws. I will try it our and report back here.

(just FYI...: I opened another issue/ request here: https://github.com/aws-samples/pyflink-getting-started/issues/13)

**Comment by patelsan** [comment]
Hi @jeremyber-aws, we spent a few hours trying to get this sample working. However, we are still getting the same errors. We are using the code as-is and have double-checked all the steps and settings explained in the video, and recreated the Kinesis app for a clean start. Please find below additional details, and let us know if you need anything else. The app bundle is almost 60MB, so I cannot upload it here but I can find a way to share if required.

 
![image](https://user-images.githubusercontent.com/898353/220395263-60cb505a-48c6-4018-ba06-6600cfcf8b04.png)

Errors:
![image](https://user-images.githubusercontent.com/898353/220395694-e50cc290-9d67-4771-a885-bc8b62f2ca0d.png)

Exception Details:
{"applicationARN":"arn:aws:kinesisanalytics:us-east-1:309613993065:application/FlinkOne-v2","applicationVersionId":4,"message":"org.apache.flink.runtime.rest.handler.RestHandlerException: Could not execute application.\n\tat org.apache.flink.runtime.webmonitor.handlers.JarRunOverrideHandler.lambda$handleRequest$4(JarRunOverrideHandler.java:248)\n\tat java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)\n\tat java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\nCaused by: java.util.concurrent.CompletionException: org.apache.flink.client.program.ProgramAbortException: java.lang.RuntimeException: Python process exits with code: 1\n\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)\n\tat java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)\n\t... 6 more\nCaused by: org.apache.flink.client.program.ProgramAbortException: java.lang.RuntimeException: Python process exits with code: 1\n\tat org.apache.flink.client.python.PythonDriver.main(PythonDriver.java:140)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)\n\tat org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)\n\tat org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)\n\tat org.apache.flink.client.deployment.application.DetachedApplicationRunner.tryExecuteJobs(DetachedApplicationRunner.java:84)\n\tat org.apache.flink.client.deployment.application.DetachedApplicationRunner.run(DetachedApplicationRunner.java:70)\n\tat org.apache.flink.runtime.webmonitor.handlers.JarRunOverrideHandler.lambda$handleRequest$3(JarRunOverrideHandler.java:239)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)\n\t... 6 more\nCaused by: java.lang.RuntimeException: Python process exits with code: 1\n\tat org.apache.flink.client.python.PythonDriver.main(PythonDriver.java:130)\n\t... 17 more\n","messageType":"ERROR","messageSchemaVersion":"1","errorCode":"CodeError.InvalidApplicationCode"}

**Comment by jeremyber-aws** [comment]
A few things to look at:

- This error says the code is invalid. Is the code working locally on your machine?
- Permissions can sometimes bubble up as errors in the code if the app cannot talk to the streams / etc. Can you validate your permissions on the app?

If you want to e-mail me your code zipped I can have a look as well. Please do check on the previous two points.

**Comment by patelsan** [comment]
Thanks for the quick reply, @jeremyber-aws 

I am on Apple M1 and have trouble installing Flink, so I cannot test the code locally. I am emailing you the code bundle.

On the permissions, I have double-checked those as well. Here is what I have - it has full access to Kinesis.

![image](https://user-images.githubusercontent.com/898353/220404166-723ca2ae-a423-43c8-9805-dcb864cdd32d.png)

Here is the auto-generated policy - this also looks good.

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "ReadCode",
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:GetObjectVersion"
            ],
            "Resource": [
                "arn:aws:s3:::kinesisapp-rulesengine/GettingStarted-v0.1.zip"
            ]
        },
        {
            "Sid": "ListCloudwatchLogGroups",
            "Effect": "Allow",
            "Action": [
                "logs:DescribeLogGroups"
            ],
            "Resource": [
                "arn:aws:logs:us-east-1:xxxxxx:log-group:*"
            ]
        },
        {
            "Sid": "ListCloudwatchLogStreams",
            "Effect": "Allow",
            "Action": [
                "logs:DescribeLogStreams"
            ],
            "Resource": [
                "arn:aws:logs:us-east-1:xxxxx:log-group:/aws/kinesis-analytics/FlinkOne-v2:log-stream:*"
            ]
        },
        {
            "Sid": "PutCloudwatchLogs",
            "Effect": "Allow",
            "Action": [
                "logs:PutLogEvents"
            ],
            "Resource": [
                "arn:aws:logs:us-east-1:xxxxx:log-group:/aws/kinesis-analytics/FlinkOne-v2:log-stream:kinesis-analytics-log-stream"
            ]
        }
    ]
}`

**Comment by jeremyber-aws** [comment]
@patelsan I think I identified the issues with the code--it seems the source and sink configurations in v1.15 changed from 1.13 causing some configuration options to be causing bugs. I just pushed an update to the code on the main and 1.15 branch--can you please check that this works for you? I have this currently running on KDA successfully.

**Comment by patelsan** [comment]
Hi @jeremyber-aws looks like it's slightly further along - we can now see the running job. However, we still see the errors on the application starts, and the job isn't able to write any records to the output stream:

![image](https://user-images.githubusercontent.com/898353/222168079-56cb4ccb-438c-4745-bf46-105dbe0b35fa.png)

It's not clear from the errors what's going on under the hood:

![image](https://user-images.githubusercontent.com/898353/222168640-8191f90e-a86d-4666-a869-7bb924c6ab2c.png)

**Comment by jeremyber-aws** [comment]
Can you please share the exceptions / errors you are seeing in the Flink Dashboard? Thanks

**Comment by patelsan** [comment]
Sure, here it is - it looks similar to the errors before your latest change, it says `InvalidApplicationCode`

{"applicationARN":"arn:aws:kinesisanalytics:us-east-1:309613993065:application/FlinkOne-v2","applicationVersionId":5,"message":"org.apache.flink.runtime.rest.handler.RestHandlerException: Could not execute application.\n\tat org.apache.flink.runtime.webmonitor.handlers.JarRunOverrideHandler.lambda$handleRequest$4(JarRunOverrideHandler.java:248)\n\tat java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)\n\tat java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\nCaused by: java.util.concurrent.CompletionException: org.apache.flink.client.program.ProgramAbortException: java.lang.RuntimeException: Python process exits with code: 1\n\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)\n\tat java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)\n\t... 6 more\nCaused by: org.apache.flink.client.program.ProgramAbortException: java.lang.RuntimeException: Python process exits with code: 1\n\tat org.apache.flink.client.python.PythonDriver.main(PythonDriver.java:140)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)\n\tat org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)\n\tat org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)\n\tat org.apache.flink.client.deployment.application.DetachedApplicationRunner.tryExecuteJobs(DetachedApplicationRunner.java:84)\n\tat org.apache.flink.client.deployment.application.DetachedApplicationRunner.run(DetachedApplicationRunner.java:70)\n\tat org.apache.flink.runtime.webmonitor.handlers.JarRunOverrideHandler.lambda$handleRequest$3(JarRunOverrideHandler.java:239)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)\n\t... 6 more\nCaused by: java.lang.RuntimeException: Python process exits with code: 1\n\tat org.apache.flink.client.python.PythonDriver.main(PythonDriver.java:130)\n\t... 17 more\n","messageType":"ERROR","messageSchemaVersion":"1","errorCode":"CodeError.InvalidApplicationCode"}

**Comment by jeremyber-aws** [comment]
Interesting--so the job is starting up and processing records in the source, but then says InvalidApplicationCode and fails? 

A quick aside: in the Flink Dashboard it will never show any records on the Records Sent if it is going outside of Apache Flink. That's why seeing 0 in your Records Sent tab is not surprising. This could be something else that would need further investigation.

Attached is a screenshot of the bundled application jar (current latest code on git) running on KDA

![image](https://user-images.githubusercontent.com/74626212/222244476-b35522b6-d8b4-480b-bbc7-0c1850b2c5f0.png)

**Comment by jeremyber-aws** [comment]
After investigation it was confirmed these samples are working.
